### ISSUE TITLE
Session Tracking

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#166]
We have been tracking session info in the clients for some time but we need to expand on this area some more to provide session dashboards. This will allow us to:

* Display dashboards with users affected
* List all sessions and allow you to dive into them to see what occurred during that session.
* Update the exceptions page with a view of what happened in that session right before the error occurred.

### Server
- [x] Add new event plugin step to lookup or create a new session start event. Cache value would be the document id for the start event. Allowing us to continually update the document with last activity.
- [x] Batch last activity document updates so that we don't relentlessly update the start event. Update once every X seconds.
- [x] Create a job or cache behavior that creates a session end for any expired sessions that are still in the cache. This will allow us to query for active sessions and sessions that have ended. This will update the session start event with the session duration and set last activity to the end time of the session.
- [x] Should we have an upgrade plugin that drops environment info and user info for existing events? Need to make sure that data does not change between events and if it does change, we would need to break the data out into stuff that is specific to the session and stuff that is specific to the event.
- [ ] Add new project_users  Denormalize the user identity data into a new elastic index (keyed on user id & project id)?
    - [ ] These should be long lived, but maybe we should consider cleaning them up after a certain amount of inactivity.
    - [ ] Do we need to keep it in sync with user info on session start event?
    - [ ] Would we update the user last active time on the heart beat or only on session end?

### JavaScript Client
- [ ] Make the script load async from cdn and collect any runtime errors. We need to promote this as the best option so we can rev the script faster. We should move bower and npm install methods to a side note.
- [ ] Better track session start, maybe set a session guid and time of client creation time and submit it when the first event is submitted. We should check a cookie or local storage for an existing session id.
- [ ] Send heartbeat from the client as well as performance metrics from window.performance. We'd also have to track the Node process startup/runtime time as part of the metrics.
- [ ] Only the session start event should contain environment & user info.
   * What should happen if someone calls EventBuilder.setIdentity()?

### .NET Client
- [ ] Better track session start, maybe set a session guid and time of client creation time and submit it when the first event is submitted.
- [x] Submit Session End on exit.
- [x] I'm not sure if we need to send a heartbeat for this.
- [x] Only the session start event should contain environment & user info.
   * What should happen if someone calls EventBuilder.setIdentity()?

**Comment by niemyjski** [comment]
.NET Client Updates
* https://github.com/exceptionless/Exceptionless.Net/commit/e06373e6493b96dafa7c24e27ea7ed5b6c5372d2
* https://github.com/exceptionless/Exceptionless.Net/commit/90da26fd86f8b3a363370f4dd8d1caa0cd8d5bf9
* https://github.com/exceptionless/Exceptionless.Net/commit/26c0d7f26341b8f0c0d26cacd2c30ffd3c40fd89

**Comment by niemyjski** [comment]
https://github.com/exceptionless/Exceptionless/tree/session

**Comment by niemyjski** [comment]
# NET Client

Seems that we would want the ability to send a heartbeat only on wpf and winform clients. We may even want to specify a default session id that is used by default on these clients (would use this session id even when the user is set and only changed when the user is changed), There are two scenarios of which we would want to send heat beats:

1. User specified a sessionid
2. Set the user on the config object.
  a. What happens if the there is no user on startup?
  b. What happens if the user is changed at runtime or via EventBuilder? Should a session stop and start event be triggered if so how? There are no events that get fired when this happens...

I think this could be solved by doing the following steps.
1. Move the UseSessions() Extension method to only the winforms and wpf client.
2. Since it's a single session the session manager will continue to work as expected on only these clients.
3. Create a Heartbeat manager or event that is fired when default data is changed. Then we can flow these changes through (unregistering existing heartbeat and registering a new one..)

**Comment by niemyjski** [comment]
New concept for linking together events..

Let's assume I have a session start… it has a single reference id… I have a page view event… it has a single reference id...

Now I have an event that happened inside of the page view and it sets 2 extended properties… 1 that points to the page view event and 1 that points to the session event. From the client I just call SetEventReference(“session”, sessionRefId)  SetEventReference(“view”, viewRefId)
