### ISSUE TITLE
Improved notifications

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#177]
The goal of notifications is to keep you informed without overwhelming you with too much information. It would be nice to know when things change (marked as fixed), a project is getting above normal exceptions, etc. Below are some issues that have been raised by others on how we can make notifications better.

### Objectives
* [ ] [Additional information on all emails (tags, descriptions, user identity)](https://github.com/exceptionless/Exceptionless/issues/136).
* [ ] [Ability to configure rules based on types, tags](https://github.com/exceptionless/Exceptionless/issues/76), [time of day](https://github.com/exceptionless/Exceptionless/issues/92), or [number of exceptions](https://github.com/exceptionless/Exceptionless/issues/176).
* [ ] [Send a periodic digest email based on activity](https://github.com/exceptionless/Exceptionless/issues/69)
* [ ] [Ability to snooze notifications for a period of time](https://github.com/exceptionless/Exceptionless/issues/92).
* [ ] [Don't send as many emails if there hasn't been any changes in activity](https://github.com/exceptionless/Exceptionless/issues/176). Example a user hasn't configured there project shouldn't get a daily notification saying they are Exceptionless every day.

### Third Party Integrations
Provide a easy way to manage third party integrations. Currently these integrations can be done with zapier. **We should define what the default message should look like.**
* [ ] [Slack](https://github.com/exceptionless/Exceptionless/issues/87)
* [ ] [Hipchat](https://github.com/exceptionless/Exceptionless/issues/81)

### Suggestions
* @webcoda [suggested](https://github.com/exceptionless/Exceptionless/issues/76) that it would be really nice to be able to send an alert to any user (even if they are not part of the system).

**Comment by HenrikHoyer** [comment]
Please add an "daily/weekly/monthly" option

**Comment by HenrikHoyer** [comment]
Please remove the "congrats, no event was logged" mails - they are just noise

**Comment by niemyjski** [comment]
@ejsmith what do you think about not sending dailies if there are no events? Could lead me to think that notifications are not working or we have not yet configured our project. We do have project is configured flag. Maybe we add configuration required emails and option to not send.

**Comment by HenrikHoyer** [comment]
I want to receive exceptions from you, not the normal case :-) All monitoring systems we use only send notifications on exceptions/deviations - none are sending "everything ok mails".

But if your current users are depending on these "everything ok" mails, then add a "send summary mails even if no exceptions has been logged" flag (imho with default = no)

**Comment by davidkeaveny** [comment]
HipChat integration would be useful for certain critical events, such as a new type of error. As long as  you can just the dial on noise vs signal then you're OK.

**Comment by ejsmith** [comment]
Yeah we absolutely have to do a good job with our signal to noise ratio

**Comment by jakejgordon** [comment]
The biggest thing I've noticed so far in the email notifications is that if there is a new exception I'd rather have the full stack trace in the email so I can quickly decide whether I need to go in and investigate or whether I should ignore it (for now). Of course the "new error" part is the hard part but I don't have any reason to think you'd mess that up :smile:

**Comment by niemyjski** [comment]
1. Add snooze actions to stack
2. make it easy to trigger snooze actions from emails
3. Add stack trace to email.
4. Keep track of emails and stop spamming emails. It's crazy. We gotta figure out how much were sending and stop sending streams of emails. Emails should be important!

**Comment by niemyjski** [comment]
We need to look at our own email inbox and see how we can ditch 90% of our emails.

**Comment by niemyjski** [comment]
For error emails we should have the link open to the stack trace tab for quick viewing as well as add the stack trace to the emails as previously noted.

**Comment by niemyjski** [comment]
Here is what our current thought process is for working notifications starting today (finally).

- [ ] We update our email templates and make them easier to edit and add content.
   - [ ] We are thinking about using https://mjml.io or (https://github.com/leemunroe/responsive-html-email-template combined with https://putsmail.com/inliner) to quickly generate valid markup from simple html.
   - [ ] Then we can test our emails using a service like [litmus](https://litmus.com/checklist/emails/public/d432046)
   - [ ] we need to figure out a way to easily update our razor templates or find a better way to generate our emails from the email templates above.
- [ ] Next, we are going to add additional information as stated above to emails.
   - [ ] Add tags
   - [ ] Stack traces and more
- [ ]  We need to identify ways to reduce noise of emails
   - [ ] Identify sources of noise by looking at all our current inboxes.
   - [ ] Look into doing [anomaly detection](https://www.elastic.co/blog/implementing-a-statistical-anomaly-detector-part-1)

There is a lot to do but here are the first steps. We want to do everything on this issue but we feel like these are the first steps that need to occur..

**Comment by ngarnier** [comment]
Hey @niemyjski, seems like you decided to go with FFE. I'd really love to know more about what made you go for this framework rather than MJML 🙂 .

Cheers!

**Comment by niemyjski** [comment]
@ngarnier I think both FFE and MJML were in a close running and have a large community base and both great solutions. We went with FFE because we felt it was a bit cleaner syntax (with inky) overall and more aligned with what we are using (lots of people using handlebars already with zurb, which we are going to use server side to do a second pass on the template). It felt like it had less of a learning curve. For example doing partial templates is pretty straight forward in FFE and I'm not sure I even seen an example of it in your docs and am not sure if it's possible.

I do think MJML is a bit sexier, and we have some friends who use it in their react projects (it’s how I heard about it). I'm wondering If our project was in react, if we would have leaned more to pick miml.

**Comment by ngarnier** [comment]
Thanks a lot for the feedback @niemyjski! 

Regarding partials, it's done with [mj-include](https://mjml.io/documentation/#mj-include). If you're talking about templating languages, it's true we prefer not to implement our own but rather enable users to use the one they want. 

About React, we're actually dropping it in the next version (see the [MJML 4 announcement](https://medium.com/mjml-making-responsive-email-easy/hey-were-entirely-rebuilding-mjml-from-scratch-announcing-mjml-v4-ae92f83b725b)) to improve performances, so it shouldn't be the main argument. Rather than using React, the [JSON format of MJML](https://mjml.io/documentation/#using-mjml-in-json) makes it really easy to build/manipulate a responsive email programatically. 

Thanks again for the feedback and feel free to reach out if you have any question regarding MJML!

**Comment by niemyjski** [comment]
Thanks for the update and I'll follow the project and v4. For us, having our server side stuff in .net, we'd have to prerender the templates or rewrite our mail job to be a node app (doable but a pain as we'd have to hook into our queues). So we wouldn't get the perf benefits of vnext, but it does sound like it's going to make your lives easier and less of a hack transforming the html :).

One of the things I think FFE does better at least out of the box is having convention / structure for the body of the email and then a partial for the content. I think if you went this route in your samples it would go a long way (I remember looking at your sample repo and you had thrive header, thrive body and thrive something and it was confusing as they all seemed to contain the same content...) Most of the content in the samples is slightly duplicated from one to the next. You're probably always going to have the same header and footer throughout your app so why specify it multiple times. It was nice to dig into and just update the main body in FFE. Please correct me if I'm wrong, I spent an hour or two looking at both :)

**Comment by ngarnier** [comment]
Oh yes you're right about having to run your own node app. Another option would be to use the [MJML API](https://mjml.io/api/documentation/) but it does add a dependency to your email system. 

Regarding the thrive examples, I see. They were meant to illustrate the different advancement steps of the email for a tutorial rather than how to use partials, but it makes sense that it might have been confusing now. We'll work to improve the documentation to reflect this better as it's really easy to do with [mj-include](https://mjml.io/documentation/#mj-include).

I'm glad you appreciate it, I didn't mean to overflow your issue's thread but rather to learn what we can do better, so thanks again for your answers!

**Comment by niemyjski** [comment]
We need to add rules for overage emails so you can opt out of them.

**Comment by niemyjski** [comment]
We should also look into something like https://image-charts.com for awesome charts in emails

**Comment by niemyjski** [comment]
> @ejsmith  we should add the count for each item in the most frequent list on the summary email. I like that I can see the list of the top issues for the day, but seems like I would want to know how many times they happened. I think we should do top 5 and then under that put “X other issues occurred N times” and that is a link to view the list of all the stacks that happened that day.

**Comment by niemyjski** [comment]
We should send an email the first time you are throttled every day.

**Comment by niemyjski** [comment]
We need the ability to opt out of new 404 messages as well.

**Comment by niemyjski** [comment]
"I'd like to request a feature enhancement. I would like to request the ability to only receive the daily project summary emails if there are items logged. I dont' want to get emails basically saying "Nothing to report today.""

**Comment by niemyjski** [comment]
"Somewhat. That is mostly how I currently have it set up. We are not marking anything critical or fixed at the moment so I only have new issues set up. I agree with the noise, but it is easy to miss something if it does not get addressed the first time. I wish there was some sort of expiration where if you still have the same issue after X amount of days it is treated as a new issue again. I just don’t want something to get missed and at the same point I don’t want developers to be required to keep exceptionless up on a tab at all times. I was just trying to think of the best way to not miss anything. I have a separate chatroom setup just for exceptionless to limit the noise as well."

**Comment by niemyjski** [comment]
+1 hipchat

**Comment by niemyjski** [comment]
Added: ability to set what time daily notifications go out.

**Comment by ejsmith** [comment]
Closing this as part of an issue cleanup.

This is an older umbrella issue that mixes many notification ideas across email, in-app notifications, integrations, billing, and rules. The app now has more concrete notification settings and delivery paths, and any remaining work should be tracked as focused issues for a specific notification scenario.

If a particular notification behavior is still needed, please open a smaller issue with the trigger, audience, delivery channel, and expected opt-in/opt-out behavior.
