### ISSUE TITLE
Elastic 7.0 support and Index Improvements

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#332]
#While we add support for [elasticsearch 6](https://github.com/exceptionless/Exceptionless/issues/331#issuecomment-344604049) we should also fix all known index issues as outlined here:

- [x] Convert Foundatio Parsers
- [x] Convert Foundatio Repositories
- [x] Searching custom extended data field of type string not returning results [#325]
- [x] Look into and see if any work needs to be done on OS Level Filtering [#324]
- [x] Look into indexing url segments or at least the domain name [#323]
- [x] Look into analyzer/tokenizer to see if we can remove punctuations [#301]
- [x] Look into wildcard search settings for optimal perf.
- [x] Test data migration in dev environment
- [x] Full round of testing in dev against migrated data
- [x] Figure out why the charts don't have as many data points as they should have
- [x] Make new storage queues? Possibly stop doing post archives
- [x] Use prod as app scope
- [x] Migrate data to prod
- [x] Setup and verify snapshots are running
- [x] Stop production application and let queues drain
- [x] Upgrade application to ES7
- [x] Do incremental reindex to get data current from old ES
- [x] Start application
- [x] Delete all old resources (ES5, etc)
- [x] Profit

**Comment by niemyjski** [comment]
Looks like there may be an issue with the query parser for issue #325, the query seems to be generated incorrectly some of the time.

**Comment by einarbey** [comment]
Hi 

i have a new setup of elasticsearch and exceptionless and i get this error 

Error creating the index stacks-v1: Original: (400 - WebException) The remote server returned an error: (400) Bad Request.
Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [stacks]: [include_in_all] is not allowed for indices created on or after version 6.0.0 as [_all] is deprecated. As a replacement, you can use an [copy_to] on mapping fields to create your own catch all field." CausedBy: "Type: mapper_parsing_exception Reason: "[include_in_all] is not allowed for indices created on or after version 6.0.0 as [_all] is deprecated. As a replacement, you can use an [copy_to] on mapping fields to create your own catch all field.""

i am running elasticsearch 6.x how can i manually create this index with out having to install elastic 5.x ?

**Comment by niemyjski** [comment]
We do not support elasticsearch 6, you'll have to use elasticsearch 5.

**Comment by woshilangdanger** [comment]
When can elasticsearch 6.0 be supported?

**Comment by niemyjski** [comment]
We're skipping elastic search completely and going to 7. Work is/has being done in the Foundatio parsers and repositories which is a massive undertaking and should be done within the month (I hope). We don't have a date set but it's a lot of work.

**Comment by DevlinSchoonraad** [comment]
Hi

Any ETA on when Elastic 7.0 support and Index Improvements will be ready?

**Comment by niemyjski** [comment]
The repositories and parsers are done, we're actively working towards migrating them.

**Comment by DevlinSchoonraad** [comment]
Thanks Blake, We use Elastic 7 and currently need to install separate servers for version 5 just for Exceptionless.

**Comment by niemyjski** [comment]
we're working through the failing unit tests getting much closer. You can follow our progress on the elastic branch.

**Comment by niemyjski** [comment]
@DevlinSchoonraad We just got our very first build passing for elastic and docker ci images (`exceptionless/api-ci:6.0.3516-pre` and `exceptionless/job-ci:6.0.3516-pre`) are up. We have not done any testing on this yet but the integration and unit tests are now passing. If you could help test this in a test environment and report any issues to us that would be a huge huge help.

**Comment by DevlinSchoonraad** [comment]
Hi

I cloned the repo and switched to feature/elastic7, when I `docker-compose up` I get the following error: 

C:\src\OSS\Exceptionless [feature/elastic7 ≡]
λ  docker compose up
docker: 'compose' is not a docker command.
See 'docker --help'
C:\src\OSS\Exceptionless [feature/elastic7 ≡]
λ  docker-compose up
Creating network "exceptionless_default" with the default driver
Creating volume "exceptionless_esdata" with local driver
Creating volume "exceptionless_appdata" with local driver
Creating volume "exceptionless_ssldata" with local driver
Pulling ui (exceptionless/ui:latest)...
latest: Pulling from exceptionless/ui
1ab2bdfe9778: Pull complete
f50f9bfaef26: Pull complete
eef791162233: Pull complete
5747027cbe1c: Pull complete
e80208d3f34e: Pull complete
d9ff94dc3a76: Pull complete
baaf447dde8d: Pull complete
03d3bc154e19: Pull complete
Digest: sha256:6e56fcb3b866a540b77d01d713d4837a1ff5fdbd3df3441115f926f353e56e89
Status: Downloaded newer image for exceptionless/ui:latest
Pulling elasticsearch (exceptionless/elasticsearch:7.4.0)...
7.4.0: Pulling from exceptionless/elasticsearch
d8d02d457314: Pull complete
a0fe4757966a: Pull complete
af323c430ce5: Pull complete
2a71ef3bd98b: Pull complete
c56e1e386724: Pull complete
1e56fdd350c5: Pull complete
16d320661b98: Pull complete
2d2c81c7988d: Pull complete
7ea3ce5b63e9: Pull complete
75c4fa466458: Pull complete
Digest: sha256:8d0aa2c4bfa7e20e9c237ad4b9347948442fe3fb8bdbf71c12c14f6f10ac7582
Status: Downloaded newer image for exceptionless/elasticsearch:7.4.0
Pulling kibana (kibana/kibana:7.4.0)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN].Y
ERROR: pull access denied for kibana/kibana, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ejsmith** [comment]
It looks like you ran `docker compose` vs docker-compose`.

**Comment by DevlinSchoonraad** [comment]
`docker-compose up` has similar result, even after docker login

c:\src\OSS\Exceptionless>docker login --username blabla etc...
Login Succeeded

c:\src\OSS\Exceptionless>docker-compose up
Pulling kibana (kibana/kibana:7.4.0)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling kibana (kibana/kibana:7.4.0)...
ERROR: pull access denied for kibana/kibana, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ejsmith** [comment]
@DevlinSchoonraad Ok, I just updated that to be the correct image for kibana. Can you try again?

**Comment by ejsmith** [comment]
> Thanks Blake, We use Elastic 7 and currently need to install separate servers for version 5 just for Exceptionless.

We just finally deployed ES7 to production. 🎉
